language: rust
#sudo: required
dist: trusty
rust:
  - stable
  - beta
  - nightly
cache: cargo
addons:
  postgresql: '9.5'
script:
  - cargo test --features diesel-uuid
env:
  global:
    - PG_DATABASE_URL=postgres://postgres@localhost/
