[package]
authors = ["Brandon W Maister <quodlibetor@gmail.com>"]
name = "uuid-b64"
version = "0.1.0"
license = "Apache-2.0/MIT"
readme = "README.md"
categories = ["encoding", "value-formatting"]
repository = "https://github.com/quodlibetor/uuid-b64"

[dependencies]
base64 = { git = "https://github.com/alicemaz/rust-base64", branch = "encode-slice" }
diesel-derive-newtype = { git = "https://github.com/quodlibetor/diesel-derive-newtype", branch = "diesel-017", optional = true }
diesel = { version = ">=0.16,<1.0", features = ["uuid"], optional = true }
error-chain = "0.11.0"
inlinable_string = { version = "0.1.0", features = ["serde"] }
lazy_static = "0.2.9"
serde = { version = "1.0.15", optional = true }
uuid = { version = ">0.4.0,<0.6", features = ["use_std", "v4"] }

[features]
default-features = ["serde"]
diesel-uuid = ["diesel-derive-newtype", "diesel"]

[dev-dependencies]
serde_json = "1.0"
serde_derive = "1.0"
diesel = { version = ">=0.16,<1.0", features = ["postgres", "uuid"] }
